### 전체 회원 조회
GET http://localhost:8888/admin/accounts



### 회원 조회
GET /accounts/{id}


### 프로젝트 별 회원 조회
GET /projects/accounts/{projectId}


### 회원 가입
POST /accounts

### kimsiyeon 조회
GET http://localhost:8888/accounts/kimsiyeon

### 회원이 정보 수정 (상태 수정 불가)
PATCH http://localhost:8888/accounts/kimsiyeon
Content-Type: application/json

{
  "password": "ksy",
  "email": "swanshawn715@gmail.com",
  "name": "tlllll"
}


### 회원 탈퇴
DELETE /accounts/{id}